create table USERS
(
    ID INTEGER NOT NULL IDENTITY,
    USERNAME VARCHAR(1000) NOT NULL,
    PASSWORD_HASH VARBINARY(1024) NOT NULL,
    PASSWORD_SALT VARBINARY(1024) NOT NULL

    CONSTRAINT PK_USER PRIMARY KEY (ID)
)
GO